language: python
python:
  - "3.6"
install:
  - pip install -r requirements-dev.txt
script:
  - ./manage.py test --settings=copernicus.testsettings
notifications:
  email:
    recipients:
      - purepython@eaudeweb.ro
