version: '2'

services:
  app:
    image: eeacms/copernicus-insitu-db:latest
    container_name: insitu.app
    ports:
      - 5050:5000
    environment:
      - DJANGO_MIGRATE=yes
      - DJANGO_COLLECT_STATIC=yes
      - DJANGO_INDEX_CONTENT=yes
      - UWSGI_PORT=5000
    env_file:
      - ./docker/postgres.env
      - docker/app.env
    depends_on:
      - postgres
      - elasticsearch
    volumes:
      - staticdata:/var/local/static

  postgres:
    image: eeacms/postgres:latest
    container_name: insitu.postgres
    environment:
      - TZ=Europe/Copenhagen
    env_file:
      - ./docker/postgres.env
    volumes:
      - postgresdata:/var/lib/postgresql/data

  backupdb:
    image: eeacms/pg_dump:latest
    container_name: insitu.backupdb
    depends_on:
      - postgres
    env_file:
      - ./docker/postgres.env
    volumes:
      - staticdata:/var/local/static
    command: /bin/sh -c 'pg_dump -U $$POSTGRES_USER -h $$POSTGRES_HOST $$POSTGRES_DBNAME | gzip > /var/local/static/insitu.sql.gz'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    container_name: insitu.elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

volumes:
  staticdata:
    driver: local
  postgresdata:
    driver: local
  esdata:
    driver: local
